version: "3.7"

services:
  elasticsearch:
    image: elasticsearch:8.4.2
    container_name: quap-elasticsearch
    hostname: quap-elasticsearch
    deploy:
        resources:
            limits:
              memory: 4096M
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - quap_volume_elasticsearch_data:/usr/share/elasticsearch/data
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
    networks:
      - quap_net

  tika:
    image: apache/tika:latest
    container_name: quap-tika
    hostname: quap-tika
    ports:
      - 9998:9998
    networks:
      - quap_net

  postgresql:
    image: postgres
    container_name: quap-postgresql
    hostname: quap-postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - quap_volume_postgres_data:/var/lib/postgresql/data/
    networks:
      - quap_net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quap-app
    depends_on:
      - elasticsearch
      - tika
      - postgresql
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    ports:
      - 9100:9100
    environment:
        - ELASTICSEARCH_HOST=quap-elasticsearch
        - ELASTICSEARCH_PORT=9200
        - TIKA_HOST=quap-tika
        - TIKA_PORT=9998
        - POSTGRESQL_HOST=quap-postgresql
        - POSTGRESQL_PORT=5432
    # todo volume for cache
    networks:
      - quap_net


volumes:
  quap_volume_elasticsearch_data:
  quap_volume_postgres_data:

networks:
  quap_net:
    driver: bridge
