version: "3.7"

services:
  elasticsearch:
    image: elasticsearch:8.4.2
    container_name: quap-elasticsearch
    hostname: quap-elasticsearch
    deploy:
        resources:
            limits:
              memory: 4096M
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - quap_volume_elasticsearch_data:/usr/share/elasticsearch/data
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
    networks:
      - backend-network

  tika:
    image: apache/tika:latest
    container_name: quap-tika
    hostname: quap-tika
    ports:
      - 9998:9998
    networks:
      - backend-network

  postgresql:
    image: postgres
    container_name: quap-postgresql
    hostname: quap-postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - quap_volume_postgres_data:/var/lib/postgresql/data/
    networks:
      - backend-network

  redis:
    image: redis
    container_name: quap-redis
    hostname: quap-redis
    ports:
      - 6379:6379
    volumes:
      - quap_volume_redis_data:/data
    networks:
      - backend-network

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: quap-backend
    hostname: quap-backend
    depends_on:
      - elasticsearch
      - tika
      - postgresql
      - redis
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    ports:
      - 9100:9100
    environment:
      - ELASTICSEARCH_HOST=quap-elasticsearch
      - ELASTICSEARCH_PORT=9200
      - TIKA_HOST=quap-tika
      - TIKA_PORT=9998
      - POSTGRESQL_HOST=quap-postgresql
      - POSTGRESQL_PORT=5432
      - REDIS_HOST=quap-redis
      - REDIS_PORT=6379
    networks:
      - backend-network
      - frontend-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: quap-frontend
    hostname: quap-frontend
    depends_on:
      - backend
    ports:
      - 9000:9000
    environment:
      - BACKEND_HOST=quap-backend
      - BACKEND_PORT=9100
    networks:
      - frontend-network


volumes:
  quap_volume_elasticsearch_data:
  quap_volume_postgres_data:
  quap_volume_redis_data:

networks:
  backend-network:
    driver: bridge
  frontend-network:
    driver: bridge
